# Generated by Django 4.1.4 on 2023-01-29 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('lekarz_id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Lekarz',
                'verbose_name_plural': 'Lekarz',
            },
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('pacjent_id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('Lekarz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lekarz')),
            ],
            options={
                'verbose_name': 'Pacjent',
                'verbose_name_plural': 'Pacjent',
            },
        ),
    ]
